class CountryMap:
    def __init__(self):
        self.country_map = {
            'Afghanistan': 'Afghanistan',
            'Albanië': 'Albania',
            'Algerije': 'Algeria',
            'Andorra': 'Andorra',
            'Angola': 'Angola',
            'Antigua en Barbuda': 'Antigua and Barbuda',
            'Argentinië': 'Argentina',
            'Armenië': 'Armenia',
            'Australië': 'Australia',
            'Oostenrijk': 'Austria',
            'Azerbeidzjan': 'Azerbaijan',
            'Bahama\'s': 'Bahamas',
            'Bahrein': 'Bahrain',
            'Bangladesh': 'Bangladesh',
            'Barbados': 'Barbados',
            'Wit-Rusland': 'Belarus',
            'België': 'Belgium',
            'Belize': 'Belize',
            'Benin': 'Benin',
            'Bhutan': 'Bhutan',
            'Bolivia': 'Bolivia',
            'Bosnië en Herzegovina': 'Bosnia and Herzegovina',
            'Botswana': 'Botswana',
            'Brazilië': 'Brazil',
            'Brunei': 'Brunei',
            'Bulgarije': 'Bulgaria',
            'Burkina Faso': 'Burkina Faso',
            'Burundi': 'Burundi',
            'Kaapverdië': 'Cabo Verde',
            'Cambodja': 'Cambodia',
            'Kameroen': 'Cameroon',
            'Canada': 'Canada',
            'Centraal-Afrikaanse Republiek': 'Central African Republic',
            'Tsjaad': 'Chad',
            'Chili': 'Chile',
            'China': 'China',
            'Colombia': 'Colombia',
            'Comoren': 'Comoros',
            'Congo-Brazzaville': 'Congo (Brazzaville)',
            'Congo-Kinshasa': 'Congo (Kinshasa)',
            'Costa Rica': 'Costa Rica',
            'Kroatië': 'Croatia',
            'Cuba': 'Cuba',
            'Cyprus': 'Cyprus',
            'Tsjechië': 'Czech Republic',
            'Denemarken': 'Denmark',
            'Djibouti': 'Djibouti',
            'Dominica': 'Dominica',
            'Dominicaanse Republiek': 'Dominican Republic',
            'Oost-Timor': 'East Timor',
            'Ecuador': 'Ecuador',
            'Egypte': 'Egypt',
            'El Salvador': 'El Salvador',
            'Equatoriaal-Guinea': 'Equatorial Guinea',
            'Eritrea': 'Eritrea',
            'Estland': 'Estonia',
            'Eswatini': 'Eswatini',
            'Ethiopië': 'Ethiopia',
            'Fiji': 'Fiji',
            'Finland': 'Finland',
            'Frankrijk': 'France',
            'Gabon': 'Gabon',
            'Gambia': 'Gambia',
            'Georgië': 'Georgia',
            'Duitsland': 'Germany',
            'Ghana': 'Ghana',
            'Griekenland': 'Greece',
            'Grenada': 'Grenada',
            'Guatemala': 'Guatemala',
            'Guinee': 'Guinea',
            'Guinee-Bissau': 'Guinea-Bissau',
            'Guyana': 'Guyana',
            'Haïti': 'Haiti',
            'Honduras': 'Honduras',
            'Hongarije': 'Hungary',
            'IJsland': 'Iceland',
            'India': 'India',
            'Indonesië': 'Indonesia',
            'Iran': 'Iran',
            'Irak': 'Iraq',
            'Ierland': 'Ireland',
            'Israël': 'Israel',
            'Italië': 'Italy',
            'Ivoorkust': 'Ivory Coast',
            'Jamaica': 'Jamaica',
            'Japan': 'Japan',
            'Jordanië': 'Jordan',
            'Kazachstan': 'Kazakhstan',
            'Kenia': 'Kenya',
            'Kiribati': 'Kiribati',
            'Noord-Korea': 'North Korea',
            'Zuid-Korea': 'South Korea',
            'Kosovo': 'Kosovo',  # Partially recognized
            'Koeweit': 'Kuwait',
            'Kirgizië': 'Kyrgyzstan',
            'Laos': 'Laos',
            'Letland': 'Latvia',
            'Libanon': 'Lebanon',
            'Lesotho': 'Lesotho',
            'Liberia': 'Liberia',
            'Libië': 'Libya',
            'Liechtenstein': 'Liechtenstein',
            'Litouwen': 'Lithuania',
            'Luxemburg': 'Luxembourg',
            'Madagaskar': 'Madagascar',
            'Malawi': 'Malawi',
            'Maleisië': 'Malaysia',
            'Maldiven': 'Maldives',
            'Mali': 'Mali',
            'Malta': 'Malta',
            'Marokko': 'Morocco',
            'Mauritanië': 'Mauritania',
            'Mauritius': 'Mauritius',
            'Mexico': 'Mexico',
            'Micronesië': 'Micronesia',
            'Moldavië': 'Moldova',
            'Monaco': 'Monaco',
            'Mongolië': 'Mongolia',
            'Montenegro': 'Montenegro',
            'Mozambique': 'Mozambique',
            'Myanmar': 'Myanmar',
            'Namibië': 'Namibia',
            'Nauru': 'Nauru',
            'Nepal': 'Nepal',
            'Nederland': 'Netherlands',
            'Nieuw-Zeeland': 'New Zealand',
            'Nicaragua': 'Nicaragua',
            'Niger': 'Niger',
            'Nigeria': 'Nigeria',
            'Noord-Macedonië': 'North Macedonia',
            'Noorwegen': 'Norway',
            'Oman': 'Oman',
            'Pakistan': 'Pakistan',
            'Palau': 'Palau',
            'Panama': 'Panama',
            'Papoea-Nieuw-Guinea': 'Papua New Guinea',
            'Paraguay': 'Paraguay',
            'Peru': 'Peru',
            'Filipijnen': 'Philippines',
            'Polen': 'Poland',
            'Portugal': 'Portugal',
            'Qatar': 'Qatar',
            'Roemenië': 'Romania',
            'Rusland': 'Russia',
            'Rwanda': 'Rwanda',
            'Saint Kitts en Nevis': 'Saint Kitts and Nevis',
            'Saint Lucia': 'Saint Lucia',
            'Saint Vincent en de Grenadines': 'Saint Vincent and the Grenadines',
            'Samoa': 'Samoa',
            'San Marino': 'San Marino',
            'Sao Tomé en Principe': 'Sao Tome and Principe',
            'Saoedi-Arabië': 'Saudi Arabia',
            'Senegal': 'Senegal',
            'Servië': 'Serbia',
            'Seychellen': 'Seychelles',
            'Sierra Leone': 'Sierra Leone',
            'Singapore': 'Singapore',
            'Slovenië': 'Slovenia',
            'Slowakije': 'Slovakia',
            'Salomonseilanden': 'Solomon Islands',
            'Somalië': 'Somalia',
            'Zuid-Afrika': 'South Africa',
            'Zuid-Soedan': 'South Sudan',
            'Spanje': 'Spain',
            'Sri Lanka': 'Sri Lanka',
            'Soedan': 'Sudan',
            'Suriname': 'Suriname',
            'Zweden': 'Sweden',
            'Zwitserland': 'Switzerland',
            'Syrië': 'Syria',
            'Tadzjikistan': 'Tajikistan',
            'Tanzania': 'Tanzania',
            'Thailand': 'Thailand',
            'Togo': 'Togo',
            'Tonga': 'Tonga',
            'Trinidad en Tobago': 'Trinidad and Tobago',
            'Tunesië': 'Tunisia',
            'Turkije': 'Turkey',
            'Turkmenistan': 'Turkmenistan',
            'Tuvalu': 'Tuvalu',
            'Oeganda': 'Uganda',
            'Oekraïne': 'Ukraine',
            'Verenigde Arabische Emiraten': 'United Arab Emirates',
            'Verenigd Koninkrijk': 'United Kingdom',
            'Uruguay': 'Uruguay',
            'Oezbekistan': 'Uzbekistan',
            'Vanuatu': 'Vanuatu',
            'Vaticaanstad': 'Vatican City',
            'Venezuela': 'Venezuela',
            'Vietnam': 'Vietnam',
            'Jemen': 'Yemen',
            'Zambia': 'Zambia',
            'Zimbabwe': 'Zimbabwe',
            'Taiwan': 'Taiwan',  # Partially recognized
            'Palestina': 'Palestine',  # Partially recognized
            'Westelijke Sahara': 'Western Sahara',  # Disputed territory
            'Engeland': 'United Kingdom',
            'Schotland': 'United Kingdom',
            'Wales': 'United Kingdom',
            'Groot-Brittannië': 'United Kingdom'
        }

    def get_country_name(self, country_name_dutch):
        return self.country_map.get(country_name_dutch, country_name_dutch)